# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run.
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 10

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Install example deps
        run: cd example && yarn && cd ..

      - name: Install example-expo deps
        run: cd example-expo && yarn && cd ..

      - name: Install deps
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Types
        run: yarn typecheck

      - name: Test
        run: yarn test-only
